package com.coding.meet.listviewapp

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ListView
import android.widget.Toast

class CustomArrayAdapterActivity : AppCompatActivity() {
    val countryList = arrayListOf(
        Country("AD", "Andorra", R.drawable.flag_ad),
        Country("AE", "United Arab Emirates", R.drawable.flag_ae),
        Country("AF", "Afghanistan", R.drawable.flag_af),
        Country("AG", "Antigua and Barbuda", R.drawable.flag_ag),
        Country("AI", "Anguilla", R.drawable.flag_ai),
        Country("AL", "Albania", R.drawable.flag_al),
        Country("AM", "Armenia", R.drawable.flag_am),
        Country("AN", "Netherlands Antilles", R.drawable.flag_an),
        Country("AO", "Angola", R.drawable.flag_ao),
        Country("AQ", "Antarctica", R.drawable.flag_aq),
        Country("AR", "Argentina", R.drawable.flag_ar),
        Country("AS", "American Samoa", R.drawable.flag_as),
        Country("AT", "Austria", R.drawable.flag_at),
        Country("AU", "Australia", R.drawable.flag_au),
        Country("AW", "Aruba", R.drawable.flag_aw),
        Country("AZ", "Azerbaijan", R.drawable.flag_az),
        Country("BA", "Bosnia and Herzegovina", R.drawable.flag_ba),
        Country("BB", "Barbados", R.drawable.flag_bb),
        Country("BD", "Bangladesh", R.drawable.flag_bd),
        Country("BE", "Belgium", R.drawable.flag_be),
        Country("BF", "Burkina Faso", R.drawable.flag_bf),
        Country("BG", "Bulgaria", R.drawable.flag_bg),
        Country("BH", "Bahrain", R.drawable.flag_bh),
        Country("BI", "Burundi", R.drawable.flag_bi),
        Country("BJ", "Benin", R.drawable.flag_bj),
        Country("BL", "Saint Barthelemy", R.drawable.flag_bl),
        Country("BM", "Bermuda", R.drawable.flag_bm),
        Country("BN", "Brunei", R.drawable.flag_bn),
        Country("BO", "Bolivia", R.drawable.flag_bo),
        Country("BR", "Brazil", R.drawable.flag_br),
        Country("BS", "Bahamas", R.drawable.flag_bs),
        Country("BT", "Bhutan", R.drawable.flag_bt),
        Country("BW", "Botswana", R.drawable.flag_bw),
        Country("BY", "Belarus", R.drawable.flag_by),
        Country("BZ", "Belize", R.drawable.flag_bz),
        Country("CA", "Canada", R.drawable.flag_ca),
        Country("CC", "Cocos Islands", R.drawable.flag_cc),
        Country("CD", "Democratic Republic of the Congo", R.drawable.flag_cd),
        Country("CF", "Central African Republic", R.drawable.flag_cf),
        Country("CG", "Republic of the Congo", R.drawable.flag_cg),
        Country("CH", "Switzerland", R.drawable.flag_ch),
        Country("CI", "Ivory Coast", R.drawable.flag_ci),
        Country("CK", "Cook Islands", R.drawable.flag_ck),
        Country("CL", "Chile", R.drawable.flag_cl),
        Country("CM", "Cameroon", R.drawable.flag_cm),
        Country("CN", "China", R.drawable.flag_cn),
        Country("CO", "Colombia", R.drawable.flag_co),
        Country("CR", "Costa Rica", R.drawable.flag_cr),
        Country("CU", "Cuba", R.drawable.flag_cu),
        Country("CV", "Cape Verde", R.drawable.flag_cv),
        Country("CW", "Curacao", R.drawable.flag_cw),
        Country("CX", "Christmas Island", R.drawable.flag_cx),
        Country("CY", "Cyprus", R.drawable.flag_cy),
        Country("CZ", "Czech Republic", R.drawable.flag_cz),
        Country("DE", "Germany", R.drawable.flag_de),
        Country("DJ", "Djibouti", R.drawable.flag_dj),
        Country("DK", "Denmark", R.drawable.flag_dk),
        Country("DM", "Dominica", R.drawable.flag_dm),
        Country("DO", "Dominican Republic", R.drawable.flag_do),
        Country("DZ", "Algeria", R.drawable.flag_dz),
        Country("EC", "Ecuador", R.drawable.flag_ec),
        Country("EE", "Estonia", R.drawable.flag_ee),
        Country("EG", "Egypt", R.drawable.flag_eg),
        Country("EH", "Western Sahara", R.drawable.flag_eh),
        Country("ER", "Eritrea", R.drawable.flag_er),
        Country("ES", "Spain", R.drawable.flag_es),
        Country("ET", "Ethiopia", R.drawable.flag_et),
        Country("FI", "Finland", R.drawable.flag_fi),
        Country("FJ", "Fiji", R.drawable.flag_fj),
        Country("FK", "Falkland Islands", R.drawable.flag_fk),
        Country("FM", "Micronesia", R.drawable.flag_fm),
        Country("FO", "Faroe Islands", R.drawable.flag_fo),
        Country("FR", "France", R.drawable.flag_fr),
        Country("GA", "Gabon", R.drawable.flag_ga),
        Country("GB", "United Kingdom", R.drawable.flag_gb),
        Country("GD", "Grenada", R.drawable.flag_gd),
        Country("GE", "Georgia", R.drawable.flag_ge),
        Country("GG", "Guernsey", R.drawable.flag_gg),
        Country("GH", "Ghana", R.drawable.flag_gh),
        Country("GI", "Gibraltar", R.drawable.flag_gi),
        Country("GL", "Greenland", R.drawable.flag_gl),
        Country("GM", "Gambia", R.drawable.flag_gm),
        Country("GN", "Guinea", R.drawable.flag_gn),
        Country("GQ", "Equatorial Guinea", R.drawable.flag_gq),
        Country("GR", "Greece", R.drawable.flag_gr),
        Country("GT", "Guatemala", R.drawable.flag_gt),
        Country("GU", "Guam", R.drawable.flag_gu),
        Country("GW", "Guinea-Bissau", R.drawable.flag_gw),
        Country("GY", "Guyana", R.drawable.flag_gy),
        Country("HK", "Hong Kong", R.drawable.flag_hk),
        Country("HN", "Honduras", R.drawable.flag_hn),
        Country("HR", "Croatia", R.drawable.flag_hr),
        Country("HT", "Haiti", R.drawable.flag_ht),
        Country("HU", "Hungary", R.drawable.flag_hu),
        Country("ID", "Indonesia", R.drawable.flag_id),
        Country("IE", "Ireland", R.drawable.flag_ie),
        Country("IL", "Israel", R.drawable.flag_il),
        Country("IM", "Isle of Man", R.drawable.flag_im),
        Country("IN", "India", R.drawable.flag_in),
        Country("IO", "British Indian Ocean Territory", R.drawable.flag_io),
        Country("IQ", "Iraq", R.drawable.flag_iq),
        Country("IR", "Iran", R.drawable.flag_ir),
        Country("IS", "Iceland", R.drawable.flag_is),
        Country("IT", "Italy", R.drawable.flag_it),
        Country("JE", "Jersey", R.drawable.flag_je),
        Country("JM", "Jamaica", R.drawable.flag_jm),
        Country("JO", "Jordan", R.drawable.flag_jo),
        Country("JP", "Japan", R.drawable.flag_jp),
        Country("KE", "Kenya", R.drawable.flag_ke),
        Country("KG", "Kyrgyzstan", R.drawable.flag_kg),
        Country("KH", "Cambodia", R.drawable.flag_kh),
        Country("KI", "Kiribati", R.drawable.flag_ki),
        Country("KM", "Comoros", R.drawable.flag_km),
        Country("KN", "Saint Kitts and Nevis", R.drawable.flag_kn),
        Country("KP", "North Korea", R.drawable.flag_kp),
        Country("KR", "South Korea", R.drawable.flag_kr),
        Country("KW", "Kuwait", R.drawable.flag_kw),
        Country("KY", "Cayman Islands", R.drawable.flag_ky),
        Country("KZ", "Kazakhstan", R.drawable.flag_kz),
        Country("LA", "Laos", R.drawable.flag_la),
        Country("LB", "Lebanon", R.drawable.flag_lb),
        Country("LC", "Saint Lucia", R.drawable.flag_lc),
        Country("LI", "Liechtenstein", R.drawable.flag_li),
        Country("LK", "Sri Lanka", R.drawable.flag_lk),
        Country("LR", "Liberia", R.drawable.flag_lr),
        Country("LS", "Lesotho", R.drawable.flag_ls),
        Country("LT", "Lithuania", R.drawable.flag_lt),
        Country("LU", "Luxembourg", R.drawable.flag_lu),
        Country("LV", "Latvia", R.drawable.flag_lv),
        Country("LY", "Libya", R.drawable.flag_ly),
        Country("MA", "Morocco", R.drawable.flag_ma),
        Country("MC", "Monaco", R.drawable.flag_mc),
        Country("MD", "Moldova", R.drawable.flag_md),
        Country("ME", "Montenegro", R.drawable.flag_me),
        Country("MF", "Saint Martin", R.drawable.flag_mf),
        Country("MG", "Madagascar", R.drawable.flag_mg),
        Country("MH", "Marshall Islands", R.drawable.flag_mh),
        Country("MK", "Macedonia", R.drawable.flag_mk),
        Country("ML", "Mali", R.drawable.flag_ml),
        Country("MM", "Myanmar", R.drawable.flag_mm),
        Country("MN", "Mongolia", R.drawable.flag_mn),
        Country("MO", "Macao", R.drawable.flag_mo),
        Country("MP", "Northern Mariana Islands", R.drawable.flag_mp),
        Country("MR", "Mauritania", R.drawable.flag_mr),
        Country("MS", "Montserrat", R.drawable.flag_ms),
        Country("MT", "Malta", R.drawable.flag_mt),
        Country("MU", "Mauritius", R.drawable.flag_mu),
        Country("MV", "Maldives", R.drawable.flag_mv),
        Country("MW", "Malawi", R.drawable.flag_mw),
        Country("MX", "Mexico", R.drawable.flag_mx),
        Country("MY", "Malaysia", R.drawable.flag_my),
        Country("MZ", "Mozambique", R.drawable.flag_mz),
        Country("NA", "Namibia", R.drawable.flag_na),
        Country("NC", "New Caledonia", R.drawable.flag_nc),
        Country("NE", "Niger", R.drawable.flag_ne),
        Country("NG", "Nigeria", R.drawable.flag_ng),
        Country("NI", "Nicaragua", R.drawable.flag_ni),
        Country("NL", "Netherlands", R.drawable.flag_nl),
        Country("NO", "Norway", R.drawable.flag_no),
        Country("NP", "Nepal", R.drawable.flag_np),
        Country("NR", "Nauru", R.drawable.flag_nr),
        Country("NU", "Niue", R.drawable.flag_nu),
        Country("NZ", "New Zealand", R.drawable.flag_nz),
        Country("OM", "Oman", R.drawable.flag_om),
        Country("PA", "Panama", R.drawable.flag_pa),
        Country("PE", "Peru", R.drawable.flag_pe),
        Country("PF", "French Polynesia", R.drawable.flag_pf),
        Country("PG", "Papua New Guinea", R.drawable.flag_pg),
        Country("PH", "Philippines", R.drawable.flag_ph),
        Country("PK", "Pakistan", R.drawable.flag_pk),
        Country("PL", "Poland", R.drawable.flag_pl),
        Country("PM", "Saint Pierre and Miquelon", R.drawable.flag_pm),
        Country("PN", "Pitcairn", R.drawable.flag_pn),
        Country("PR", "Puerto Rico", R.drawable.flag_pr),
        Country("PS", "Palestinian", R.drawable.flag_ps),
        Country("PT", "Portugal", R.drawable.flag_pt),
        Country("PW", "Palau", R.drawable.flag_pw),
        Country("PY", "Paraguay", R.drawable.flag_py),
        Country("QA", "Qatar", R.drawable.flag_qa),
        Country("RE", "Reunion", R.drawable.flag_re),
        Country("RO", "Romania", R.drawable.flag_ro),
        Country("RS", "Serbia", R.drawable.flag_rs),
        Country("RU", "Russia", R.drawable.flag_ru),
        Country("RW", "Rwanda", R.drawable.flag_rw),
        Country("SA", "Saudi Arabia", R.drawable.flag_sa),
        Country("SB", "Solomon Islands", R.drawable.flag_sb),
        Country("SC", "Seychelles", R.drawable.flag_sc),
        Country("SD", "Sudan", R.drawable.flag_sd),
        Country("SE", "Sweden", R.drawable.flag_se),
        Country("SG", "Singapore", R.drawable.flag_sg),
        Country("SH", "Saint Helena", R.drawable.flag_sh),
        Country("SI", "Slovenia", R.drawable.flag_si),
        Country("SJ", "Svalbard and Jan Mayen", R.drawable.flag_sj),
        Country("SK", "Slovakia", R.drawable.flag_sk),
        Country("SL", "Sierra Leone", R.drawable.flag_sl),
        Country("SM", "San Marino", R.drawable.flag_sm),
        Country("SN", "Senegal", R.drawable.flag_sn),
        Country("SO", "Somalia", R.drawable.flag_so),
        Country("SR", "Suriname", R.drawable.flag_sr),
        Country("SS", "South Sudan", R.drawable.flag_ss),
        Country("ST", "Sao Tome and Principe", R.drawable.flag_st),
        Country("SV", "El Salvador", R.drawable.flag_sv),
        Country("SX", "Sint Maarten", R.drawable.flag_sx),
        Country("SY", "Syria", R.drawable.flag_sy),
        Country("SZ", "Swaziland", R.drawable.flag_sz),
        Country("TC", "Turks and Caicos Islands", R.drawable.flag_tc),
        Country("TD", "Chad", R.drawable.flag_td),
        Country("TG", "Togo", R.drawable.flag_tg),
        Country("TH", "Thailand", R.drawable.flag_th),
        Country("TJ", "Tajikistan", R.drawable.flag_tj),
        Country("TK", "Tokelau", R.drawable.flag_tk),
        Country("TL", "East Timor", R.drawable.flag_tl),
        Country("TM", "Turkmenistan", R.drawable.flag_tm),
        Country("TN", "Tunisia", R.drawable.flag_tn),
        Country("TO", "Tonga", R.drawable.flag_to),
        Country("TR", "Turkey", R.drawable.flag_tr),
        Country("TT", "Trinidad and Tobago", R.drawable.flag_tt),
        Country("TV", "Tuvalu", R.drawable.flag_tv),
        Country("TW", "Taiwan", R.drawable.flag_tw),
        Country("TZ", "Tanzania", R.drawable.flag_tz),
        Country("UA", "Ukraine", R.drawable.flag_ua),
        Country("UG", "Uganda", R.drawable.flag_ug),
        Country("US", "United State", R.drawable.flag_us),
        Country("UY", "Uruguay", R.drawable.flag_uy),
        Country("UZ", "Uzbekistan", R.drawable.flag_uz),
        Country("VA", "Vatican", R.drawable.flag_va),
        Country("VC", "Saint Vincent and the Grenadines", R.drawable.flag_vc),
        Country("VE", "Venezuela", R.drawable.flag_ve),
        Country("VG", "British Virgin Islands", R.drawable.flag_vg),
        Country("VI", "U.S. Virgin Islands", R.drawable.flag_vi),
        Country("VN", "Vietnam", R.drawable.flag_vn),
        Country("VU", "Vanuatu", R.drawable.flag_vu),
        Country("WF", "Wallis and Futuna", R.drawable.flag_wf),
        Country("WS", "Samoa", R.drawable.flag_ws),
        Country("XK", "Kosovo", R.drawable.flag_xk),
        Country("YE", "Yemen", R.drawable.flag_ye),
        Country("YT", "Mayotte", R.drawable.flag_yt),
        Country("ZA", "South Africa", R.drawable.flag_za),
        Country("ZM", "Zambia", R.drawable.flag_zm),
        Country("ZW", "Zimbabwe", R.drawable.flag_zw)
        )
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_custom_array_adapter)

        val customLV = findViewById<ListView>(R.id.customLV)
        customLV.adapter = CountryAdapter(this,countryList)
//        customLV.setOnItemClickListener { adapterView, view, pos, l ->
//            Toast.makeText(this,countryList[pos].code,Toast.LENGTH_LONG).show()
//        }
//        customLV.setOnItemLongClickListener { adapterView, view, pos, l ->
//            Toast.makeText(this,"Position:$pos",Toast.LENGTH_LONG).show()
//            true
//        }
    }
}